# Cấu hình build
[build]
  # Thư mục chứa các Netlify Functions
  functions = "netlify/functions/"

# Chuyển hướng để frontend có thể gọi API một cách dễ dàng
# Tất cả các request tới /api/* sẽ được chuyển đến Netlify Function tương ứng
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
