# netlify.toml

# Cấu hình Build
[build]
  # Thư mục chứa các serverless function của bạn.
  # Netlify sẽ tự động tìm và build các file JavaScript trong này.
  functions = "netlify/functions"

# Cấu hình chuyển hướng (Redirects and Rewrites)
# Đây là phần rất quan trọng cho các ứng dụng trang đơn (Single Page Application - SPA)
[[redirects]]
  # Chuyển hướng tất cả các yêu cầu không khớp (ví dụ: khi người dùng F5 trang)
  from = "/*"
  # Về lại file index.html để ứng dụng JavaScript có thể xử lý routing.
  to = "/index.html"
  # Mã trạng thái 200 có nghĩa là "OK" và nó sẽ không thay đổi URL trên trình duyệt.
  status = 200
