# netlify.toml

# Cài đặt xây dựng cơ bản
[build]
  # Thư mục chứa các file HTML, CSS, JS tĩnh để publish
  publish = "." 
  # Thư mục chứa các serverless functions
  functions = "netlify/functions"

# Cài đặt chuyển hướng (không cần thiết cho dự án này nhưng nên biết)
# [[redirects]]
#   from = "/old-path"
#   to = "/new-path"
#   status = 301
