[build]
  # Thư mục chứa các file HTML, CSS, JS của bạn để Netlify hiển thị
  publish = "public"
  # Thư mục chứa các Netlify Functions của bạn
  functions = "netlify/functions"

# Chuyển hướng các yêu cầu API đến functions
[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat"
  status = 200

[[redirects]]
  from = "/api/search"
  to = "/.netlify/functions/search-and-summarize"
  status = 200
