# netlify.toml

# Cấu hình Build
[build]
  functions = "netlify/functions"

# Cấu hình chuyển hướng (Redirects and Rewrites)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Plugin đặc biệt để tự động cài đặt dependencies cho Functions
[[plugins]]
package = "@netlify/plugin-functions-install-core"
