# Cấu hình build cho Netlify
[build]
  # Thư mục chứa các Netlify Functions
  functions = "netlify/functions/"

# Plugin để tự động cài đặt dependencies cho các functions
[[plugins]]
  package = "@netlify/plugin-functions-install-core"
